### PR TITLE
Fixed syntax error from superfluous parenthesis

### PR DESCRIPTION
**Pull request by viccie30**

### CODE REVIEW

**Review by wjwwood — APPROVED** [review]

**Comment by viccie30** [comment]
That's what I call fast!

**Comment by dirk-thomas** [comment]
Leaving it up to @DorianScholz / @kunaltyagi to merge this and make a new patch release...

**Comment by DorianScholz** [comment]
LGTM
@dirk-thomas It looks like I don't have write access to this repo anymore, so I can neither merge nor release... I guess this is due to the splitting of the repos?

**Comment by dirk-thomas** [comment]
> It looks like I don't have write access to this repo anymore

I added both of you as collaborators with admin access to this repo as well as the corresponding release repo.

**Comment by DorianScholz** [comment]
Fix is released in 0.4.9
Status of merge into rosdistro can be seen here:
https://github.com/ros/rosdistro/pulls?utf8=%E2%9C%93&q=is%3Apr%20rqt_shell%3A%200.4.9-0

Thanks for your contribution!

**Pull request merged**
